/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as DemoStoreImport } from './routes/demo.store'
import { Route as DemoConvexImport } from './routes/demo.convex'
import { Route as AuthVerifyEmailIndexImport } from './routes/auth/verify-email/index'
import { Route as AuthResetPasswordIndexImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthForgotPasswordIndexImport } from './routes/auth/forgot-password/index'
import { Route as DemoStartServerFuncsImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestImport } from './routes/demo.start.api-request'
import { Route as DemoFormSimpleImport } from './routes/demo.form.simple'
import { Route as DemoFormAddressImport } from './routes/demo.form.address'
import { Route as AuthTwoFactorSetupIndexImport } from './routes/auth/twoFactor/setup/index'
import { Route as AuthTwoFactorResetIndexImport } from './routes/auth/twoFactor/reset/index'
import { Route as AuthResetPasswordVerifyEmailIndexImport } from './routes/auth/reset-password/verify-email/index'
import { Route as AuthResetPasswordTwoFactorIndexImport } from './routes/auth/reset-password/twoFactor/index'
import { Route as AuthTwoFactorTotpSetupIndexImport } from './routes/auth/twoFactor/totp/setup/index'
import { Route as AuthTwoFactorSecurityKeyRegisterIndexImport } from './routes/auth/twoFactor/security-key/register/index'
import { Route as AuthTwoFactorPasskeyRegisterIndexImport } from './routes/auth/twoFactor/passkey/register/index'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const DemoStoreRoute = DemoStoreImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRoute,
} as any)

const DemoConvexRoute = DemoConvexImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthResetPasswordIndexRoute = AuthResetPasswordIndexImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DemoStartServerFuncsRoute = DemoStartServerFuncsImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRoute,
} as any)

const DemoStartApiRequestRoute = DemoStartApiRequestImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRoute,
} as any)

const DemoFormSimpleRoute = DemoFormSimpleImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRoute,
} as any)

const DemoFormAddressRoute = DemoFormAddressImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRoute,
} as any)

const AuthTwoFactorSetupIndexRoute = AuthTwoFactorSetupIndexImport.update({
  id: '/twoFactor/setup/',
  path: '/twoFactor/setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthTwoFactorResetIndexRoute = AuthTwoFactorResetIndexImport.update({
  id: '/twoFactor/reset/',
  path: '/twoFactor/reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthResetPasswordVerifyEmailIndexRoute =
  AuthResetPasswordVerifyEmailIndexImport.update({
    id: '/reset-password/verify-email/',
    path: '/reset-password/verify-email/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthResetPasswordTwoFactorIndexRoute =
  AuthResetPasswordTwoFactorIndexImport.update({
    id: '/reset-password/twoFactor/',
    path: '/reset-password/twoFactor/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthTwoFactorTotpSetupIndexRoute =
  AuthTwoFactorTotpSetupIndexImport.update({
    id: '/twoFactor/totp/setup/',
    path: '/twoFactor/totp/setup/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthTwoFactorSecurityKeyRegisterIndexRoute =
  AuthTwoFactorSecurityKeyRegisterIndexImport.update({
    id: '/twoFactor/security-key/register/',
    path: '/twoFactor/security-key/register/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthTwoFactorPasskeyRegisterIndexRoute =
  AuthTwoFactorPasskeyRegisterIndexImport.update({
    id: '/twoFactor/passkey/register/',
    path: '/twoFactor/passkey/register/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexImport
      parentRoute: typeof rootRoute
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressImport
      parentRoute: typeof rootRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleImport
      parentRoute: typeof rootRoute
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestImport
      parentRoute: typeof rootRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password/twoFactor/': {
      id: '/auth/reset-password/twoFactor/'
      path: '/reset-password/twoFactor'
      fullPath: '/auth/reset-password/twoFactor'
      preLoaderRoute: typeof AuthResetPasswordTwoFactorIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password/verify-email/': {
      id: '/auth/reset-password/verify-email/'
      path: '/reset-password/verify-email'
      fullPath: '/auth/reset-password/verify-email'
      preLoaderRoute: typeof AuthResetPasswordVerifyEmailIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/twoFactor/reset/': {
      id: '/auth/twoFactor/reset/'
      path: '/twoFactor/reset'
      fullPath: '/auth/twoFactor/reset'
      preLoaderRoute: typeof AuthTwoFactorResetIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/twoFactor/setup/': {
      id: '/auth/twoFactor/setup/'
      path: '/twoFactor/setup'
      fullPath: '/auth/twoFactor/setup'
      preLoaderRoute: typeof AuthTwoFactorSetupIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/twoFactor/passkey/register/': {
      id: '/auth/twoFactor/passkey/register/'
      path: '/twoFactor/passkey/register'
      fullPath: '/auth/twoFactor/passkey/register'
      preLoaderRoute: typeof AuthTwoFactorPasskeyRegisterIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/twoFactor/security-key/register/': {
      id: '/auth/twoFactor/security-key/register/'
      path: '/twoFactor/security-key/register'
      fullPath: '/auth/twoFactor/security-key/register'
      preLoaderRoute: typeof AuthTwoFactorSecurityKeyRegisterIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/twoFactor/totp/setup/': {
      id: '/auth/twoFactor/totp/setup/'
      path: '/twoFactor/totp/setup'
      fullPath: '/auth/twoFactor/totp/setup'
      preLoaderRoute: typeof AuthTwoFactorTotpSetupIndexImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
  AuthResetPasswordTwoFactorIndexRoute: typeof AuthResetPasswordTwoFactorIndexRoute
  AuthResetPasswordVerifyEmailIndexRoute: typeof AuthResetPasswordVerifyEmailIndexRoute
  AuthTwoFactorResetIndexRoute: typeof AuthTwoFactorResetIndexRoute
  AuthTwoFactorSetupIndexRoute: typeof AuthTwoFactorSetupIndexRoute
  AuthTwoFactorPasskeyRegisterIndexRoute: typeof AuthTwoFactorPasskeyRegisterIndexRoute
  AuthTwoFactorSecurityKeyRegisterIndexRoute: typeof AuthTwoFactorSecurityKeyRegisterIndexRoute
  AuthTwoFactorTotpSetupIndexRoute: typeof AuthTwoFactorTotpSetupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
  AuthResetPasswordTwoFactorIndexRoute: AuthResetPasswordTwoFactorIndexRoute,
  AuthResetPasswordVerifyEmailIndexRoute:
    AuthResetPasswordVerifyEmailIndexRoute,
  AuthTwoFactorResetIndexRoute: AuthTwoFactorResetIndexRoute,
  AuthTwoFactorSetupIndexRoute: AuthTwoFactorSetupIndexRoute,
  AuthTwoFactorPasskeyRegisterIndexRoute:
    AuthTwoFactorPasskeyRegisterIndexRoute,
  AuthTwoFactorSecurityKeyRegisterIndexRoute:
    AuthTwoFactorSecurityKeyRegisterIndexRoute,
  AuthTwoFactorTotpSetupIndexRoute: AuthTwoFactorTotpSetupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/auth/': typeof AuthIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/auth/reset-password/twoFactor': typeof AuthResetPasswordTwoFactorIndexRoute
  '/auth/reset-password/verify-email': typeof AuthResetPasswordVerifyEmailIndexRoute
  '/auth/twoFactor/reset': typeof AuthTwoFactorResetIndexRoute
  '/auth/twoFactor/setup': typeof AuthTwoFactorSetupIndexRoute
  '/auth/twoFactor/passkey/register': typeof AuthTwoFactorPasskeyRegisterIndexRoute
  '/auth/twoFactor/security-key/register': typeof AuthTwoFactorSecurityKeyRegisterIndexRoute
  '/auth/twoFactor/totp/setup': typeof AuthTwoFactorTotpSetupIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/auth': typeof AuthIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/auth/reset-password/twoFactor': typeof AuthResetPasswordTwoFactorIndexRoute
  '/auth/reset-password/verify-email': typeof AuthResetPasswordVerifyEmailIndexRoute
  '/auth/twoFactor/reset': typeof AuthTwoFactorResetIndexRoute
  '/auth/twoFactor/setup': typeof AuthTwoFactorSetupIndexRoute
  '/auth/twoFactor/passkey/register': typeof AuthTwoFactorPasskeyRegisterIndexRoute
  '/auth/twoFactor/security-key/register': typeof AuthTwoFactorSecurityKeyRegisterIndexRoute
  '/auth/twoFactor/totp/setup': typeof AuthTwoFactorTotpSetupIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/demo/convex': typeof DemoConvexRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/auth/': typeof AuthIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/auth/reset-password/twoFactor/': typeof AuthResetPasswordTwoFactorIndexRoute
  '/auth/reset-password/verify-email/': typeof AuthResetPasswordVerifyEmailIndexRoute
  '/auth/twoFactor/reset/': typeof AuthTwoFactorResetIndexRoute
  '/auth/twoFactor/setup/': typeof AuthTwoFactorSetupIndexRoute
  '/auth/twoFactor/passkey/register/': typeof AuthTwoFactorPasskeyRegisterIndexRoute
  '/auth/twoFactor/security-key/register/': typeof AuthTwoFactorSecurityKeyRegisterIndexRoute
  '/auth/twoFactor/totp/setup/': typeof AuthTwoFactorTotpSetupIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo/convex'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/auth/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/reset-password/twoFactor'
    | '/auth/reset-password/verify-email'
    | '/auth/twoFactor/reset'
    | '/auth/twoFactor/setup'
    | '/auth/twoFactor/passkey/register'
    | '/auth/twoFactor/security-key/register'
    | '/auth/twoFactor/totp/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/convex'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/auth'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/reset-password/twoFactor'
    | '/auth/reset-password/verify-email'
    | '/auth/twoFactor/reset'
    | '/auth/twoFactor/setup'
    | '/auth/twoFactor/passkey/register'
    | '/auth/twoFactor/security-key/register'
    | '/auth/twoFactor/totp/setup'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/demo/convex'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/auth/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/verify-email/'
    | '/auth/reset-password/twoFactor/'
    | '/auth/reset-password/verify-email/'
    | '/auth/twoFactor/reset/'
    | '/auth/twoFactor/setup/'
    | '/auth/twoFactor/passkey/register/'
    | '/auth/twoFactor/security-key/register/'
    | '/auth/twoFactor/totp/setup/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoConvexRoute: typeof DemoConvexRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoConvexRoute: DemoConvexRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/demo/convex",
        "/demo/store",
        "/demo/tanstack-query",
        "/demo/form/address",
        "/demo/form/simple",
        "/demo/start/api-request",
        "/demo/start/server-funcs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/",
        "/auth/forgot-password/",
        "/auth/login/",
        "/auth/register/",
        "/auth/reset-password/",
        "/auth/verify-email/",
        "/auth/reset-password/twoFactor/",
        "/auth/reset-password/verify-email/",
        "/auth/twoFactor/reset/",
        "/auth/twoFactor/setup/",
        "/auth/twoFactor/passkey/register/",
        "/auth/twoFactor/security-key/register/",
        "/auth/twoFactor/totp/setup/"
      ]
    },
    "/demo/convex": {
      "filePath": "demo.convex.tsx"
    },
    "/demo/store": {
      "filePath": "demo.store.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/demo/form/address": {
      "filePath": "demo.form.address.tsx"
    },
    "/demo/form/simple": {
      "filePath": "demo.form.simple.tsx"
    },
    "/demo/start/api-request": {
      "filePath": "demo.start.api-request.tsx"
    },
    "/demo/start/server-funcs": {
      "filePath": "demo.start.server-funcs.tsx"
    },
    "/auth/forgot-password/": {
      "filePath": "auth/forgot-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx",
      "parent": "/auth"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password/": {
      "filePath": "auth/reset-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/verify-email/": {
      "filePath": "auth/verify-email/index.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password/twoFactor/": {
      "filePath": "auth/reset-password/twoFactor/index.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password/verify-email/": {
      "filePath": "auth/reset-password/verify-email/index.tsx",
      "parent": "/auth"
    },
    "/auth/twoFactor/reset/": {
      "filePath": "auth/twoFactor/reset/index.tsx",
      "parent": "/auth"
    },
    "/auth/twoFactor/setup/": {
      "filePath": "auth/twoFactor/setup/index.tsx",
      "parent": "/auth"
    },
    "/auth/twoFactor/passkey/register/": {
      "filePath": "auth/twoFactor/passkey/register/index.tsx",
      "parent": "/auth"
    },
    "/auth/twoFactor/security-key/register/": {
      "filePath": "auth/twoFactor/security-key/register/index.tsx",
      "parent": "/auth"
    },
    "/auth/twoFactor/totp/setup/": {
      "filePath": "auth/twoFactor/totp/setup/index.tsx",
      "parent": "/auth"
    }
  }
}
ROUTE_MANIFEST_END */
